language: node_js

node_js: 
  - "stable"

env:
  - GIT_BRANCH=master

cache:
  directories:
    - "$HOME/.npm"

before_script:
  - git clone --depth=1 --branch=$GIT_BRANCH https://github.com/nicoaugereau/alexa-test.git nicoaugereau/alexa-test && cd nicoaugereau/alexa-test
  - npm ci

script:
  - mocha test/about.js
  - mocha test/frontpagedeals.js